### ISSUE TITLE
Upgrade not working

### ISSUE THREAD

**Issue by Marathon2422** [ubports/gallery-app#65] opened 2018-06-10 01:04 UTC
Upgrade gives error 7,from device updates.
Install fom openstore,disables the app altogether,
I just have a frozen icon.
Rebooting. And so on.

**Comment by StefWe** [comment] 2018-06-10 09:44
Can you post a screenshot from your error 7?
Which device you are using?
Do you run on 15.04 or 16.04?

**Comment by TronFortyTwo** [comment] 2018-06-10 09:56
Marius is working with CI to publish automatic updates to the OpenStore. Maybe the issue is with the version number, since Marius bumped to version 2.9.5 but that was already a version. It should be 2.9.10 iirc.

**Comment by Marathon2422** [comment] 2018-06-10 14:33
I am on pro5 16.04 r91
It works on my m10fhd 

(game:- 8192 will not install from openstore)

**Comment by hoh61** [comment] 2018-06-10 21:49
With 16.04 r92 on my m10fhd the shipped gallery app (2.9.5) is running with the known limitations. Updating tis the version from the open store make this app unusable.

**Comment by StefWe** [comment] 2018-06-11 14:52
@hoh61 and @Marathon2422 can you post the log files?

**Comment by hoh61** [comment] 2018-06-11 17:39
Sorry, I couldn' get rid of the installed camera app, therrfore I had to load a fresh frieza image including wiping. If you thing it will improve the situation I may repeat the whole cycle again...

**Comment by Marathon2422** [comment] 2018-06-11 22:09
Gallery vivid 2.9.8
Gallery. Xenial 2.9.5
It shows   Invalid app id
                with URL. '(null)'
Tried doing it by downloading from.   open-store.io       not working

I cannot install the game   8192      
Sorry I cant seem to copy n paste, notes or screenshots on this m10 fhd yet

**Comment by StefWe** [comment] 2018-06-12 11:00
i will play around tonight. i will report if i found something...

**Comment by Marathon2422** [comment] 2018-06-12 13:41
i have installed the game  8192 ,0n pro5 and m10fhd, by downloading from
open-store.io,and using ut-tweak-tool.the game runs and works,and shows it
is version 0.6

but ,openstore    (the app)   wants to upgrade the  8192, it goes thru the
motions of upgrading ,then goes back to the upgrade screen ,ready to
upgrade the app.

the 8192 app still works as it should and is showing it is version 0.6

just thought this might help

**Comment by StefWe** [comment] 2018-06-12 15:08
there is a new version of the gallery-app https://open-store.io/app/com.ubuntu.gallery

this version is working on my device. Maybe this will fix your problem.

**Comment by Marathon2422** [comment] 2018-06-12 15:11
Thanks , I am not where I can try it for an hour or so.

**Comment by Marathon2422** [comment] 2018-06-12 16:12
Hey, both my devices were turned on, when i got home ,i thought i would
check the Gallery app before i did anything ,and Lo and behold it is
working on both devices ( m10fhd and pro5).
       ( i may have  already installed that version ,if it was there ,about
2-3 hrs after your first email)

Thanks for your help with this    😀

( i checked the games app 8192 ,and in openstore it wants to upgrade it ,it
is just looping back to the upgrade screen ,it shows i have version )  0.6
installed .)

**Comment by StefWe** [comment] 2018-06-13 06:06
can you close this issue @Flohack74 ? Thank you..

**Closed** 2018-06-13 15:55 UTC
